name: Security & Lint Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  format-lint:
    name: Format & Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install -e ".[dev]"

      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit

      - name: Ruff Format Check
        run: ruff format --check .

      - name: Ruff Lint
        run: ruff check . --output-format=github

      - name: mypy Type Check
        run: mypy src/ || true

  security-scan:
    name: Security Scan (Bandit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit[toml]

      - name: Run Bandit Security Scan
        run: bandit -r src/ -f json -o bandit-report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-security-report
          path: bandit-report.json
